/* GENERATED by gen_pins.py FROM THE BOARD (mcu-board/pmgr_mcu.kicad_pcb).
 * Do not edit by hand, and do not regenerate from MCU-BOARD-SCHEMATIC.md -
 * the board is what gets fabricated. */
#ifndef PMGR_PINS_H
#define PMGR_PINS_H

#include <avr/io.h>

/* Data bus: all eight bits on PORTA, so a bus read is one instruction.
   The PMGR handshake timing depends on that - never split across ports. */
#define BUS_PORT      PORTA

/*
 * ADB:
 * P4.0 / PD1 PMGR_ADB = control output to an external inverting
 *                       open-collector ADB driver. ⛔ Driven OPEN-DRAIN
 *                       in software - Hi-Z asserts, LOW releases, NEVER
 *                       driven HIGH. See pmgr_adb.c and MEASUREMENTS 2.58.
 * P4.1 / PD2 FDB      = direct ADB bus sense input.
 */

/* ---- PORTA ---- */
#define VIAD0_PORT             PORTA
#define VIAD0_bm               (1U << 0)   /* PA0, TQFP 62 */
#define VIAD1_PORT             PORTA
#define VIAD1_bm               (1U << 1)   /* PA1, TQFP 63 */
#define VIAD2_PORT             PORTA
#define VIAD2_bm               (1U << 2)   /* PA2, TQFP 64 */
#define VIAD3_PORT             PORTA
#define VIAD3_bm               (1U << 3)   /* PA3, TQFP 1 */
#define VIAD4_PORT             PORTA
#define VIAD4_bm               (1U << 4)   /* PA4, TQFP 2 */
#define VIAD5_PORT             PORTA
#define VIAD5_bm               (1U << 5)   /* PA5, TQFP 3 */
#define VIAD6_PORT             PORTA
#define VIAD6_bm               (1U << 6)   /* PA6, TQFP 4 */
#define VIAD7_PORT             PORTA
#define VIAD7_bm               (1U << 7)   /* PA7, TQFP 5 */

/* ---- PORTB ---- */
#define PMREQ_N_PORT           PORTB
#define PMREQ_N_bm             (1U << 0)   /* PB0, TQFP 8 */
#define PMACK_N_PORT           PORTB
#define PMACK_N_bm             (1U << 1)   /* PB1, TQFP 9 */
#define PMINT_N_PORT           PORTB
#define PMINT_N_bm             (1U << 2)   /* PB2, TQFP 10 */
#define SYS_RST_N_PORT         PORTB
#define SYS_RST_N_bm           (1U << 3)   /* PB3, TQFP 11 */
#define RESET_N_PORT           PORTB
#define RESET_N_bm             (1U << 4)   /* PB4, TQFP 12 */
#define PMGR_RESET_N_PORT      PORTB
#define PMGR_RESET_N_bm        (1U << 5)   /* PB5, TQFP 13 */
#define VIA_TEST_PORT          PORTB
#define VIA_TEST_bm            (1U << 6)   /* PB6, TQFP 14 */
#define ONESEC_N_PORT          PORTB
#define ONESEC_N_bm            (1U << 7)   /* PB7, TQFP 15 */

/* ---- PORTC ---- */
#define SOUND_LATCH_PORT       PORTC
#define SOUND_LATCH_bm         (1U << 0)   /* PC0, TQFP 16 */
#define OFF_HOOK_PORT          PORTC
#define OFF_HOOK_bm            (1U << 1)   /* PC1, TQFP 17 */
#define SIXTYHZ_PORT           PORTC
#define SIXTYHZ_bm             (1U << 2)   /* PC2, TQFP 18 */
#define PMGCLK_F_PORT          PORTC
#define PMGCLK_F_bm            (1U << 4)   /* PC4, TQFP 22 */

/* ---- PORTD ---- */
#define ADC_IN_PORT            PORTD
#define ADC_IN_bm              (1U << 0)   /* PD0, TQFP 26 */
#define PMGR_ADB_PORT          PORTD
#define PMGR_ADB_bm            (1U << 1)   /* PD1, TQFP 27 */
#define FDB_PORT               PORTD
#define FDB_bm                 (1U << 2)   /* PD2, TQFP 28 */
#define DISP_BLANK_N_PORT      PORTD
#define DISP_BLANK_N_bm        (1U << 3)   /* PD3, TQFP 29 */
#define MODEM_INS_N_PORT       PORTD
#define MODEM_INS_N_bm         (1U << 4)   /* PD4, TQFP 30 */
#define SOUND_OFF_PORT         PORTD
#define SOUND_OFF_bm           (1U << 5)   /* PD5, TQFP 31 */
#define PMGR_PWM_PORT          PORTD
#define PMGR_PWM_bm            (1U << 6)   /* PD6, TQFP 32 */
#define PMGR_IN0_PORT          PORTD
#define PMGR_IN0_bm            (1U << 7)   /* PD7, TQFP 33 */

/* ---- PORTE ---- */
#define AKD_PORT               PORTE
#define AKD_bm                 (1U << 0)   /* PE0, TQFP 36 */
#define STOP_CLK_PORT          PORTE
#define STOP_CLK_bm            (1U << 1)   /* PE1, TQFP 37 */
#define CHRG_ON_N_PORT         PORTE
#define CHRG_ON_N_bm           (1U << 2)   /* PE2, TQFP 38 */
#define KBD_RST_N_PORT         PORTE
#define KBD_RST_N_bm           (1U << 3)   /* PE3, TQFP 39 */
#define HICHG_PORT             PORTE
#define HICHG_bm               (1U << 4)   /* PE4, TQFP 40 */
#define RING_DETECT_PORT       PORTE
#define RING_DETECT_bm         (1U << 5)   /* PE5, TQFP 41 */
#define MODEM_AB_PORT          PORTE
#define MODEM_AB_bm            (1U << 6)   /* PE6, TQFP 42 */

/* ---- PORTF ---- */
#define DBG2_PORT              PORTF
#define DBG2_bm                (1U << 3)   /* PF3, TQFP 47 */
#define DBG1_PORT              PORTF
#define DBG1_bm                (1U << 4)   /* PF4, TQFP 48 */
#define DBG0_PORT              PORTF
#define DBG0_bm                (1U << 5)   /* PF5, TQFP 49 */

/* ---- PORTG ---- */
#define SYS_PWR_N_PORT         PORTG
#define SYS_PWR_N_bm           (1U << 0)   /* PG0, TQFP 52 */
#define MINUS5_EN_PORT         PORTG
#define MINUS5_EN_bm           (1U << 1)   /* PG1, TQFP 53 */
#define SOUND_PWR_N_PORT       PORTG
#define SOUND_PWR_N_bm         (1U << 2)   /* PG2, TQFP 54 */
#define SERIAL_PWR_N_PORT      PORTG
#define SERIAL_PWR_N_bm        (1U << 3)   /* PG3, TQFP 55 */
#define MODEM_PWR_N_PORT       PORTG
#define MODEM_PWR_N_bm         (1U << 4)   /* PG4, TQFP 58 */
#define HD_PWR_N_PORT          PORTG
#define HD_PWR_N_bm            (1U << 5)   /* PG5, TQFP 59 */
#define SCC_CNTRL_PORT         PORTG
#define SCC_CNTRL_bm           (1U << 6)   /* PG6, TQFP 60 */
#define IWM_CNTRL_PORT         PORTG
#define IWM_CNTRL_bm           (1U << 7)   /* PG7, TQFP 61 */

/* ---- M50753 port -> our port transforms (checked by gen_pins.py) ----
 *
 * Apple operates on whole port BYTES in places (Power_Command; eor Port_P1
 * in BatteryManage; the sleep path). Our bit orders differ per port as a
 * consequence of the interposer routing remap. Any handler consuming a port
 * bitmap MUST apply the right transform - none of them is the identity.
 */
#define PMGR_P0_PORT        PORTG
#define PMGR_P0_EXACT_REVERSAL 1   /* our bit = 7 - P0 bit */

#define PMGR_P1_PORT        PORTE
#define PMGR_P1_SHIFT       (-1)   /* our bit = P1 bit -1 */

/* P3: SPLIT across ports ['B', 'D'] - NO byte-level transform.
 * Byte-wise code for P3 must be written bit-by-bit. */
#define PMGR_P3_SPLIT       1

#define PMGR_P4_PORT        PORTD
#define PMGR_P4_SHIFT       (+1)   /* our bit = P4 bit +1 */

/* Handshake lines are ACTIVE LOW. */
#define ASSERT_LOW(p,m)    ((p).OUT &= (uint8_t)~(m))
#define DEASSERT_HIGH(p,m) ((p).OUT |= (uint8_t)(m))
#define PIN_IS_LOW(p,m)    (((p).IN & (m)) == 0)

#endif /* PMGR_PINS_H */
