#!/usr/bin/env python3
"""Generate firmware/include/pmgr_pins.h from the FABRICATED BOARD.

Sources, in order of authority:
  1. hardware/mcu-board/pmgr_mcu.kicad_pcb  -> which net is on which U1 pin (via IPC-D-356)
  2. KiCad's AVR64DB64x-xPT symbol -> which TQFP pin is which port bit

Deliberately NOT generated from MCU-BOARD-SCHEMATIC.md: that doc has been wrong
about PMGCLK_F, KBD_RST* and the AD_FILTER/ADC_IN split. The board is the thing
that gets fabricated.
"""
import re, subprocess, sys, os, tempfile

BASE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(BASE)
CLI  = "/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli"
SYM  = "/Applications/KiCad/KiCad.app/Contents/SharedSupport/symbols/MCU_Microchip_AVR_Dx.kicad_sym"

def avr_symbol_pins():
    t = open(SYM).read()
    i = t.index('(symbol "AVR64DB64x-xPT"')
    d = 0; ins = False
    for n in range(i, len(t)):
        c = t[n]
        if c == '"': ins = not ins
        elif not ins:
            if c == '(': d += 1
            elif c == ')':
                d -= 1
                if d == 0: break
    blk = t[i:n+1]
    out = {}
    for name, num in re.findall(r'\(name "([^"]+)".{0,200}?\(number "([^"]+)"', blk, re.S):
        m = re.search(r'\bP([A-G])(\d)\b', name)
        if m: out[int(num)] = (m.group(1), int(m.group(2)))
    return out

def board_u1_nets():
    tmp = tempfile.mktemp(suffix=".d356")
    subprocess.run([CLI, "pcb", "export", "ipcd356", "--output", tmp,
                    f"{ROOT}/hardware/mcu-board/pmgr_mcu.kicad_pcb"],
                   check=True, capture_output=True)
    out = {}
    for ln in open(tmp):
        if not re.match(r'^3[12]7', ln): continue
        if ln[20:26].strip() != 'U1': continue
        net = ln[3:17].strip()
        if net and net != 'N/C': out[int(ln[27:31].strip())] = net
    os.unlink(tmp)
    return out

sym  = avr_symbol_pins()
nets = board_u1_nets()

byport = {}
for pin, net in sorted(nets.items()):
    if pin not in sym: continue
    port, bit = sym[pin]
    if net in ('+5V', 'GND', 'UPDI'): continue
    byport.setdefault(port, {})[bit] = (net, pin)

L = ['/* GENERATED by gen_pins.py FROM THE BOARD (hardware/mcu-board/pmgr_mcu.kicad_pcb).',
     ' * Do not edit by hand, and do not regenerate from MCU-BOARD-SCHEMATIC.md -',
     ' * the board is what gets fabricated. */',
     '#ifndef PMGR_PINS_H', '#define PMGR_PINS_H', '', '#include <avr/io.h>', '',
     '/* Data bus: all eight bits on PORTA, so a bus read is one instruction.',
     '   The PMGR handshake timing depends on that - never split across ports. */',
     '#define BUS_PORT      PORTA', '',
     '/*',
     ' * ADB:',
     ' * P4.0 / PD1 PMGR_ADB = control output to an external inverting',
     ' *                       open-collector ADB driver. ⛔ Driven OPEN-DRAIN',
     ' *                       in software - Hi-Z asserts, LOW releases, NEVER',
     ' *                       driven HIGH. See pmgr_adb.c and MEASUREMENTS 2.58.',
     ' * P4.1 / PD2 FDB      = direct ADB bus sense input.',
     ' */', '']
n = 0
for port in sorted(byport):
    L.append(f'/* ---- PORT{port} ---- */')
    for bit in sorted(byport[port]):
        net, pin = byport[port][bit]
        L.append(f'#define {net+"_PORT":<22} PORT{port}')
        L.append(f'#define {net+"_bm":<22} (1U << {bit})   /* P{port}{bit}, TQFP {pin} */')
        n += 1
    L.append('')
# ---- M50753 port <-> our port transforms, checked at generation time ---------
# Apple operates on whole port bytes in several places, so any handler that
# consumes or produces a port bitmap needs the right transform. These are NOT
# all the same, and none of them is the identity.
M50753_PORTS = {
 'P0': ['IWM_CNTRL','SCC_CNTRL','HD_PWR_N','MODEM_PWR_N',
        'SERIAL_PWR_N','SOUND_PWR_N','MINUS5_EN','SYS_PWR_N'],
 'P1': [None,'AKD','STOP_CLK','CHRG_ON_N','KBD_RST_N','HICHG','RING_DETECT','MODEM_AB'],
 'P3': ['RESET_N','SYS_RST_N','VIA_TEST','SOUND_OFF','ONESEC_N','PMINT_N','PMACK_N','PMREQ_N'],
 'P4': ['PMGR_ADB','FDB','DISP_BLANK_N','MODEM_INS_N'],
}
loc = {}
for port, bits in byport.items():
    for bit, (net, pin) in bits.items():
        loc[net] = (port, bit)

L += ['/* ---- M50753 port -> our port transforms (checked by gen_pins.py) ----',
      ' *',
      ' * Apple operates on whole port BYTES in places (Power_Command; eor Port_P1',
      ' * in BatteryManage; the sleep path). Our bit orders differ per port as a',
      ' * consequence of the interposer routing remap. Any handler consuming a port',
      ' * bitmap MUST apply the right transform - none of them is the identity.',
      ' */']
for pname, sigs in M50753_PORTS.items():
    placed = [(i, loc[n]) for i, n in enumerate(sigs) if n and n in loc]
    absent = [n for n in sigs if n and n not in loc]
    if absent:
        sys.exit(f"FATAL: {pname} signals missing from the board: {absent}")
    ports = {p for _, (p, _) in placed}
    if len(ports) != 1:
        L += [f'/* {pname}: SPLIT across ports {sorted(ports)} - NO byte-level transform.',
              f' * Byte-wise code for {pname} must be written bit-by-bit. */',
              f'#define PMGR_{pname}_SPLIT       1', '']
        continue
    p = ports.pop()
    shifts = {b - i for i, (_, b) in placed}
    revs   = {b - (7 - i) for i, (_, b) in placed}
    if len(shifts) == 1:
        sh = shifts.pop()
        L += [f'#define PMGR_{pname}_PORT        PORT{p}',
              f'#define PMGR_{pname}_SHIFT       ({sh:+d})   /* our bit = {pname} bit {sh:+d} */', '']
    elif len(revs) == 1:
        L += [f'#define PMGR_{pname}_PORT        PORT{p}',
              f'#define PMGR_{pname}_EXACT_REVERSAL 1   /* our bit = 7 - {pname} bit */', '']
    else:
        sys.exit(f"FATAL: {pname} on PORT{p} has no uniform transform: "
                 f"{[(i,b) for i,(_,b) in placed]}. Any byte-wise handler for "
                 f"{pname} must be reworked.")

L += ['/* Handshake lines are ACTIVE LOW. */',
      '#define ASSERT_LOW(p,m)    ((p).OUTCLR = (m))',
      '#define DEASSERT_HIGH(p,m) ((p).OUTSET = (m))',
      '#define PIN_IS_LOW(p,m)    (((p).IN & (m)) == 0)', '',
      '#endif /* PMGR_PINS_H */', '']
open(f"{BASE}/include/pmgr_pins.h", "w").write("\n".join(L))
print(f"pmgr_pins.h: {n} signals generated from the board")
